banka_full = convert_banka_to_matrix(age, job, marital, education, ...
    default, housing, loan, contact, month, day_of_week, duration, ...
    campaign, pdays, previous, poutcome, empvarrate, conspriceidx, ...
    consconfidx, euribor3m, nremployed, y);

clear 'age' 'job' 'marital' 'education' 'default' 'housing' 'loan' ...
    'contact' 'month' 'day_of_week' 'duration' 'campaign' 'pdays' ...
    'previous' 'poutcome' 'empvarrate' 'conspriceidx' 'consconfidx' ...
    'euribor3m' 'nremployed' 'y'