bank_full = convert_bank_to_matrix(age, balance1, campaign, ...
    contact, day, default, duration, education, housing, job, loan, ...
    marital, month, pdays, poutcome, previous, y);

clear 'age' 'balance1' 'campaign' 'contact' 'day' 'default' 'duration' ...
    'education' 'housing' 'job' 'loan' 'marital' 'month' 'pdays' ...
    'poutcome' 'previous' 'y'